-- Role: "DB_OWNER_USER"
-- DROP ROLE "DB_OWNER_USER";

CREATE ROLE "DB_OWNER_USER" WITH
  LOGIN
  SUPERUSER
  INHERIT
  NOCREATEDB
  CREATEROLE
  NOREPLICATION
  ENCRYPTED PASSWORD 'md5fb2917a21e99c3bba21e5361343edff6';
  
  
-- Role: "EMPLOYEE_APP_USER"
-- DROP ROLE "EMPLOYEE_APP_USER";

CREATE ROLE "EMPLOYEE_APP_USER" WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  ENCRYPTED PASSWORD 'md5fee37a3fc65ba4c73a7fc452d9f99868';